
package Game;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class Game extends javax.swing.JFrame {
    
    String answer;
    public boolean correct = true;
  
    public Game() {
        initComponents();
//       GameInitComponents();
    }
    
   
    public final void GameInitComponents() {
//         optionA.setText(this.getOptA());
//        optionA.setText("Cringe");
        
        
   
    }
    
    
    public void setOptA(String questionOptA){
        optionA.setText(questionOptA);
    }

    public void setOptB(String optB){
        optionB.setText(optB);
    }
    
    public void setOptC(String optC){
        optionC.setText(optC);
    }
    
    public void setOptD(String optD){
        optionD.setText(optD);
    }
    
    public void setQuestion(String question){
        questionDisplay.setText(question);
    }
    
    public void setAnswer(String answer){
        this.answer = answer;
    }
    
    public void setProgess(int current, int total){
        Progress.setText("Question: " + current +"/" + total);
    }
    
    public boolean checkAnswer(String input){
        boolean correct = false;
        if(this.answer.equalsIgnoreCase(input)){
            correct = true;
        }
        return correct;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        questionDisplay = new javax.swing.JLabel();
        optionA = new javax.swing.JButton();
        optionB = new javax.swing.JButton();
        optionC = new javax.swing.JButton();
        optionD = new javax.swing.JButton();
        Progress = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        questionDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionDisplay.setText("(Question Display)");

        optionA.setText("A");
        optionA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionAActionPerformed(evt);
            }
        });

        optionB.setText("B");
        optionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionBActionPerformed(evt);
            }
        });

        optionC.setText("C");
        optionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionCActionPerformed(evt);
            }
        });

        optionD.setText("D");
        optionD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionDActionPerformed(evt);
            }
        });

        Progress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Progress.setText("num of questions");

        jButton1.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questionDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optionA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Progress, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(optionB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optionC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optionD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Progress, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)))
                .addGap(24, 24, 24)
                .addComponent(questionDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optionA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionD)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void optionAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionAActionPerformed
        String input = optionA.getText();
        if(!checkAnswer(input)){
            correct = false;
            JOptionPane.showMessageDialog(null, "Wrong answer!");
            this.setVisible(false);
            SelectGameMode gameModes = new SelectGameMode();
                
            gameModes.setVisible(true);
            gameModes.setLocationRelativeTo(null);
            System.out.println("Wrong Answer");
            GameHelper.resetCount();
        }
        else{
            System.out.println("Correct Answer");
            this.setVisible(false);
            GameManager gm = new GameManager(GameHelper.gameMode);

        }
    }//GEN-LAST:event_optionAActionPerformed

    private void optionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionBActionPerformed
        String input = optionB.getText();
        if(!checkAnswer(input)){
            correct = false;
            JOptionPane.showMessageDialog(null, "Wrong answer!");
            this.setVisible(false);
            SelectGameMode gameModes = new SelectGameMode();
                
            gameModes.setVisible(true);
            gameModes.setLocationRelativeTo(null);
            System.out.println("Wrong Answer");
            GameHelper.resetCount();
        }
        else{
            System.out.println("Correct Answer");
            this.setVisible(false);
            GameManager gm = new GameManager(GameHelper.gameMode);
        }
    }//GEN-LAST:event_optionBActionPerformed

    private void optionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionCActionPerformed
        String input = optionC.getText();
        if(!checkAnswer(input)){
            correct = false;
            JOptionPane.showMessageDialog(null, "Wrong answer!");
            this.setVisible(false);
            SelectGameMode gameModes = new SelectGameMode();
                
            gameModes.setVisible(true);
            gameModes.setLocationRelativeTo(null);
            System.out.println("Wrong Answer");
            GameHelper.resetCount();
        }
        else{
            System.out.println("Correct Answer");
            this.setVisible(false);
            GameManager gm = new GameManager(GameHelper.gameMode);
        }
    }//GEN-LAST:event_optionCActionPerformed

    private void optionDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionDActionPerformed
        String input = optionD.getText();
        if(!checkAnswer(input)){
            correct = false;
            
            JOptionPane.showMessageDialog(null, "Wrong answer!");
            this.setVisible(false);
            SelectGameMode gameModes = new SelectGameMode();
                
            gameModes.setVisible(true);
            gameModes.setLocationRelativeTo(null);
            System.out.println("Wrong Answer");
            GameHelper.resetCount();
        }
        else{
            System.out.println("Correct Answer");
            this.setVisible(false);
            GameManager gm = new GameManager(GameHelper.gameMode);

        }
    }//GEN-LAST:event_optionDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Progress;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JButton optionA;
    private javax.swing.JButton optionB;
    private javax.swing.JButton optionC;
    private javax.swing.JButton optionD;
    private javax.swing.JLabel questionDisplay;
    // End of variables declaration//GEN-END:variables
}
