package Game;

public class HelpJFrameForm extends javax.swing.JFrame {

    /**
     * Creates new form Help
     */
    public HelpJFrameForm() {
        initComponents();
        newInitComponents();
    }
    
    private void newInitComponents(){
        gameInfoText.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpLabel = new javax.swing.JLabel();
        infoScrollPane = new javax.swing.JScrollPane();
        gameInfoText = new javax.swing.JTextArea();
        backToMenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        helpLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        helpLabel.setText("Help & Game Information");

        gameInfoText.setColumns(20);
        gameInfoText.setRows(5);
        gameInfoText.setText("\nCASH IS KING\nQUIZ  GAME\n\nHow to play: \nIn this game you will answer multi choice questions to earn cash.\nSelect what game mode you would like to play (if you can afford the buy in)\nand wager your cash for a possible big pay out. \n\nThere are 4 different modes you can play.\n\nLevel 1:\n        Buy in: Free\n\tReward: $300\n\tQuestions: 3\n\nLevel 2:\n        Buy in: $1000\n\tReward: $10,000\n\tQuestions: 3\n\nLevel 3:\n        Buy in: $30,000\n\tReward: $100,000\n\tQuestions: 5\n\nLevel ELITE:\n        Buy in: $100,000\n\tReward: $1,000,000\n\tQuestions: 10\n\nGood luck and have fun!");
        infoScrollPane.setViewportView(gameInfoText);

        backToMenuButton.setText("Back");
        backToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(infoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(backToMenuButton)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(helpLabel)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(helpLabel)
                .addGap(18, 18, 18)
                .addComponent(infoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backToMenuButton)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuButtonActionPerformed
        //Returns back to menu if button is selected
        this.setVisible(false);
        MenuJFrameForm menu = new MenuJFrameForm();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
    }//GEN-LAST:event_backToMenuButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMenuButton;
    private javax.swing.JTextArea gameInfoText;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JScrollPane infoScrollPane;
    // End of variables declaration//GEN-END:variables
}
